### PR TITLE
Added Wait

### PR DESCRIPTION
**Pull request by jfischoff**
Here you go

### CODE REVIEW

**Comment by alexeyzab** [comment]
@feuerbach Hi there! I'd like to help with this, but I am a bit new.
Would a proper test look something like this? I am not entirely sure.

```haskell
  , testCase "wait waits long enough" $ do
      thread <- Immortal.create $ \_ -> threadDelay maxBound
      _ <- forkIO $ threadDelay (10^4) >> Immortal.stop thread
      result <- Immortal.wait thread

      result @?= ()
```

**Comment by feuerbach** [comment]
Hi Alexey!

Perhaps you could explain your reasoning there? I don't think this would work, but maybe I am missing something.
For instance, I don't think `result @?= ()` checks anything.

I think a proper test should be something like this:

1. spawn an immortal thread to wait, say, 0.1s and then write something to a TVar
2. in the main thread, wait until the  thread finishes
3. after wait, check that the tvar is updated

The idea is that if wait doesn't wait long enough, the TVar will not be updated.

**Comment by alexeyzab** [comment]
@feuerbach My original assumption was that `Immortal.wait` would throw an exception if it didn't wait long enough. So I wanted to check that there was no exception. Which seems to be incorrect, my bad.

Thank you for explaining how this test should work, I'll work on that!

**Comment by feuerbach** [comment]
If anything throws an exception, that'd certainly lead to a test failure. But what if wait simply did nothing and returned immediately? That'd pass our existing tests (I think).

**Comment by alexeyzab** [comment]
This is what I've come up with:

```haskell
  , testCase "wait waits long enough" $ do
      tv <- atomically $ newTVar True
      thread <- Immortal.create $ \t -> do
        delay
        atomically $ writeTVar tv False
        Immortal.stop t
      _ <- Immortal.wait thread

      v <- atomically $ readTVar tv
      v @?= False
```

Is it better?

**Comment by feuerbach** [comment]
Looks great! Could you send a PR?

**Comment by alexeyzab** [comment]
Sure! Should I squash the older commits into a single one as well?

**Pull request closed without merging**
